#7. Pinheiro  - Implemente um programa que desenhe um "pinheiro" na tela, similar ao abaixo.Enriqueça o desenho com outros caracteres, simulando enfeites.
print("         *         ")
print("        ***        ")
print("       *****       ")
print("      *******      ")
print('     *********     ')
print('    ***********    ')
print('   *************   ')
print('  ***************  ')
print('        **         ')
print('        **         ')
print('       ****        ')
